name: Semgrep SAST
on: [push]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install & Run Semgrep
        run: |
          python3 -m pip install semgrep
          semgrep scan --config="p/default"
